baseURL = 'https://jmespath.site/'
languageCode = 'en-us'
title = 'JMESPath'
theme = 'jmespath'

disableKinds = ["section", "taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[module]
[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = ['wiki/_Sidebar.md']

[_build]
publishResources = false

[markup.goldmark.renderer]
unsafe= true

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'friendly'
tabWidth = 4

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

